export default [
  'Changed bed sheets',
  'Took dog out for a walk',
  'Fixed leakey roof',
  'The Cummer Museum of Art and Gardens',
  'Catty Shack Ranch Wildlife Sanctuary',
  'Friendship Fountain, Jacksonville',
  'Riverside, Jacksonville',
  'Jacksonville Fire Museum',
  'Timucuan Ecological Preserve',
  'Kingsley Plantation, Jacksonville',
  'Clark’s Fish Camp, Jacksonville',
  'Little Talbot Island State Park',
  'The Florida Theatre',
  'Japanese Garden at Jacksonville Zoo',
  'Hands-On Children’s Museum',
  'Adventure Landing',
  'Butterfly at Tree Hill Nature Center',
  'Riverside Arts Market, Jacksonville',
  'St Johns Town Center at Christmas'
];
